# مفاهیم پایه

برای شروع بهتر است با یکسری از مفاهیم آشنا شویم.

## دیدگاه و نظرات

برای نوشتن دیدگاه (Comment)
یا اجرا نکردن کدهای نوشته شده باید از 
`#`
قبل از آن‌ها استفاده شود

```r
# The Comment helps the readability of the coding
```

::: {.remark} :::
 قرار دادن دیدگاه به فهم و خوانایی کد برای دیگران و بازبینی‌های آینده کمک می‌کند.
::::::


## راهنما

ابزار راهنما (Help)
در زبان 
**R**
به ما امکان دسترسی به توضیحات مختصر هر 
شئ (Object)
را می‌دهد.

- گرفتن راهنما برای تابع خاص که نام آن را می‌دانیم:

```r
?mean
```

- انجام جستجو در تمام بسته‌های نصب شده در سیستم:

```r
??mean
```

- جستجوی کلمه یا عبارت در پرونده راهنما:

```r
help.search('weighed mean')
```

- پیدا کردن راهنما برای یک بسته

```r
help(package = 'tidyverse')
```

- پیدا کردن راهنمای توابع در همه بسته‌های موجود سایت **CRAN**

```r
RSiteSearch("mean")
```

- استفاده از سایت گوگل
([**www.google.com**](https://www.google.com/))


::: {.remark} :::
 بهترین مهارت برای یک برنامه نویس مهارت گوگل کردن است.
::::::


- پرسیدن و جستجوی سوالات در سایت 
([**stackoverflow.com**](https://stackoverflow.com/))


::: {.remark} :::
سعی کنید در ابتدای کار کل کدها را تایپ کنید و بدون فهم درست از کدها چیزی را کپی نکنید.
::::::



## محیط کاری

- پیدا کردن محیط کاری [(Working Directory)]{dir=ltr}
(جایی که در آن ورودی‌ها را گرفته و خروجی‌ها را تولید می‌کنید)

```r
getwd()
```
```output
[1] "/home/{USER}/Desktop/"
```

- تنظیم و تغییر محیط کاری

```r
setwd('/home/{USER}/Documents/')
```

- دقت داشته باشید که در زبان 
**R**
مانند لینوکس از 
`"/"`
برای جداسازی پوشه (Directory)
و زیر پوشه [(Sub Directory)]{dir=ltr}
استفاده می‌شود.

- برای  تنظیم محیط کاری بهتره از 
پروژه (Project)
در 
**RStudio**
استفاده کنید.

## اجرای کد

- راه اندازی محیط 
**R**
در ترمینال و 
اجرای مستقیم کد در 
کنسول (Console)

```bash
$ R

> my code ...
```

- ذخیره کدها در فایل متنی با پسوند 
`code.R` 
و اجرای آن با کد
`Rscript`
در کامند لاین

```bash
$ Rscript code.R
```

## چاپ کردن

```r
print("Salam Donya!")
```
```
[1] "Salam Donya!"
```

##  کلاس 

- یافتن 
نوع (Type)
یا
کلاس (Class)
یک شی


```r
typeof("Mohsen")
```
```output
[1] "character"
```

```r
class("Mohsen")
```
```output
[1] "character"
```

## پاک کردن کنسول 

برای پاک کردن کنسول می‌توانید از کلید میانبر
[`ctrl + L`]{dir=ltr}
استفاده کنید.
