# عملگرها

\[\Large
f(x_1, x_2) = x_1 \; f \; x_2
\]

عملگر (Operator)
نوع خاصی از تابع است که روی چیز‌های که در چپ و راست آن قرار گیرد،
اعمال می‌شود.


## عملگر پایپ

با استفاده از عملگر پایپ
می‌توانیم خروجی یک تابع را به عنوان وروردی به اولین آرگومان تابع بعدی دهیم

\[\Large
f(g(x)) = (fog)(x)
\]

عملگر پایپ می‌تواند کار با توابع را ساده و از تعریف متغییر‌های زیاد جلوگیری کند.


- [(`|>`)]{dir=ltr}: یک عملگر درون ساخت است.

```r
paste("Salam", "Mohsen") |> print()
```
```output
[1] "Salam Mohsen"
```

- [(`%>%`)]{dir=ltr}: باید بسته `tidyverse` را فراخانی کنیم.

```r
paste("Salam", "Mohsen") %>% print()
```
```output
[1] "Salam Mohsen"
```


## عملگرهای حسابی

عملگر حسابی اعداد را به عنوان ورودی می‌گیرد و اعمال ریاضی را اعمال می‌کند.

- جمع

```r
2 + 3
```
```output
[1] 5
```


- تفریق

```1
2 - 3
```
```output
[1] -1
```


- ضرب

```r
2 * 3
```
```output
[1] 6
```


- تقسیم

```r
2 / 3
```
```output
[1] 0.6666667
```

- باقی‌مانده تقسیم

```r
5 %% 3
```
```output
[1] 2
```


- قسمت صحیح تقسیم

```r
5 %/% 3
```
```output
[1] 1
```


- توان

```r
2^3
```
```output
[1] 8
```

استفاده از توان کسری برای جذر

```r
(4)^(1/2)
```
```output
[1] 2
```

### عملگر منطقی

عملگر منطقی مقادیر درست و غلط برمی‌گرداند.

- برابری

```r
1 == 2
```
```output
[1] FALSE
```


- نابرابری

```r
1 != 2
```
```output
[1] TRUE
```


- بزرگتری

```r
2 > 2
```
```output
[1] FALSE
```


- بزرگتری یا برابری

```r
2 >= 2
```
```output
[1] FALSE
```



- کوچکتری

```r
2 < 2
```
```output
[1] FALSE
```


- کوچکتری یا برابری

```r
2 <= 2
```
```output
[1] TRUE
```


- و

هر دو شرط اجرا می‌شود
و در صورت درست بودن هر دوی آن‌ها مقدار
`TRUE`
برمی‌گرداند در غیر این صورت مقدار
`FALSE`
برمیگرداند.

```r
1 == 2 & 1 < 2
```
```output
[1] FALSE
```

شرط دوم در صورت درست بودن شرط اول اجرا می‌شود.
و در صورت درست بودن هر دوی آن‌ها مقدار
`TRUE`
برمی‌گرداند در غیر این صورت مقدار
`FALSE`
برمیگرداند.

```r
1 == 2 && 1 < 2
```
```output
[1] FALSE
```

- یا

هر دو شرط اجرا می‌شود و در صورت درست بودن یکی از آن‌ها 
مقدار 
`TRUE`
برمی‌گرداند در غیر این صورت مقدار
`FALSE`
برمیگرداند.

```r
1 == 2 | 1 < 2
```
```output
[1] TRUE
```

شرط دوم در صورت نادرست بودن شرط اول اجرا می‌شود و اگر
یکی از آن‌ها درست بود مقدار
`TRUE`
برمی‌گرداند در غیر این صورت مقدار
`FALSE`
برمیگرداند.

```r
1 == 2 || 1 < 2
```
```output
[1] TRUE
```

- مخالف

بعد از بررسی عمل منطقی خلاف مقدار برگردانده شده را بر می‌گرداند.

```r
!(1 == 2)
```
```output
[1] TRUE
```
