# مقادیر

به طور کلی در 
**R**
برای یک 
مقدار (Value)
انواع
رشته‌ای (Character)،
عددی (Numeric)،
منطقی (Logical)
و
خالی (Null)
وجود دارد.


## رشته‌ای

عمومی ترین نوع یک مقدار، نوع رشته‌ای است که درون 
`''`
یا 
`""`
قرار می‌گیرند.


```r
class('Hello')
```
```output
[1] "character"
```

```r
class("Hello")
```
```output
[1] "character"
```

- تغییر یک مقدار به نوع رشته‌ای

```r
as.character(99)
```
```output
[1] "99"
```

- مقادیر از دست رفته رشته‌ای

```r
class(NA_character_)
```
```output
[1] "character"
```

## عددی

مقادیری که عملیات ریاضی بر آن‌ها می‌توان انجام داد.

```r
class(-1234567890)
```
```output
[1] "numeric"
```


- تغییر یک مقدار به نوع عددی

```r
as.numeric("000100.000")
```
```output
[1] 100
```



- مقادیر تعریف نشده

```r
0/0
```
```output
[1] NaN
```

```r
class(NaN)
```
```output
[1] "numeric"
```

- مقادیر عددی از دست رفته
```r
class(NA_real_)
```
```output
[1] "numeric"
```


- تغییر یک مقدار به نوع عددی
صحیح (Integer)

```r
as.integer(12.001)
```
```output
[1] 12
```

- مقادیر عددی صحیح از دست رفته

```r
class(NA_integer_)
```
```output
[1] "integer"
```

-  تغییر یک مقدار به نوع عددی
اعشاری (Double)

```r
as.double(12.001)
```
```output
[1] 12.001
```

- تغییر یک مقدار به نوع عددی
مختلط (Complex)

```r
as.complex(12.001)
```
```output
[1] 12.001+0i
```

- مقادیر عددی مختلط از دست رفته

‍‍```r
class(NA_complex_)
```
```output
[1] NA_complex_
```

## منطقی

مقادیر منطقی به صورت 
درست (True)،
غلط (False)
یا 
از دست رفته (Not Available)
برمی‌گردند.


- تغییر مقدار به نوع منطقی به این صورت است که 
`0` را غلط برمیگرداند و مقادیر غیر   `0`را درست بر می‌گرداند.


```r
as.logical(564564)
```
```output
[1] True
```

```r
as.logical(0)
```
```output
[1] FALSE
```

```r
as.logical(NA)
```
```output
[1] NA
```

### درست

- مقدار منطقی درست باید یا با حرف 
`T`
یا با حروف بزرگ
`TRUE`
نوشته شود تا به عنوان مقدار منطقی درست پذیرفته شود.


```r
class(T)
```
```output
[1] "logical"
```


```r
class(TRUE)
```
```output
[1] "logical"
```


- دیگر املاهای عبارت درست، خطا بر می‌گردانند.

```r
class(true)
```
```output
Error: object 'true' not found
```

```r
class(True)
```
```output
Error: object 'True' not found
```

- چک کردن درست بودن یک مقدار

```r
isTRUE(TRUE)
```
```output
[1] TRUE
```

### غلط

- مقدار منطقی غلط باید یا با حرف 
`F`
یا با حروف بزرگ
`FALSE`
نوشته شود تا به عنوان مقدار منطقی پذیرفته شود.

```r
class(F)
```
```output
[1] "logical"
```

```r
class(FALSE)
```
```output
[1] "logical"
```

- دیگر املاهای عبارت غلط، خطا بر می‌گردانند.

```r
class(false)
```
```output
[1] Error: object 'false' not found
```

```r
class(False)
```
```output
Error: object 'False' not found
```

- چک کردن غلط بودن

```r
isFALSE(FALSE)
```
```output
[1] TRUE
```

### از دست رفته

به مقداری که به دلایلی در دسترس نیست گویند که با 
`NA`
مشخص می‌شوند

```r
class(NA)
```
```output
[1] "logical"
```

- چک کردن از دست رفته بودن

```r
is.na(NA)
```
```output
[1] TRUE
```

## خالی

مقادیر خالی با حروف بزرگ انگلیسی به صورت 
`NULL`
مشخص می‌شوند

```r
class(NULL)
```
```output
[1] "NULL"
```

- چک کردن خالی بودن

```r
is.null(NULL)
```
```output
[1] TRUE
```
